export const FETCH_MEMBERS = 'FETCH_MEMBERS';
export const FETCH_MEMBERS_PENDING = 'FETCH_MEMBERS_PENDING';
export const FETCH_MEMBERS_REJECTED = 'FETCH_MEMBERS_REJECTED';
export const FETCH_MEMBERS_FULFILLED = 'FETCH_MEMBERS_FULFILLED';
